"""
models.py — Pydantic request/response schemas.

Money rule: amounts are always INTEGER paise on the wire.
The frontend is responsible for rupee ↔ paise conversion before sending
and after receiving. This file never touches floats for money.

Why ConfigDict (not inner class Config)?
  Pydantic v2 deprecated the inner Config class. ConfigDict is the v2-native
  way and keeps us forward-compatible with future Pydantic releases.
"""

from datetime import date as DateType
from typing import List

from pydantic import BaseModel, ConfigDict, field_validator


# ---------------------------------------------------------------------------
# Request body for POST /expenses
# ---------------------------------------------------------------------------
class ExpenseCreate(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    id: str                  # UUID generated by the client (idempotency key)
    amount: int              # PAISE — must be > 0
    category: str
    description: str
    date: str                # ISO-8601 date string "YYYY-MM-DD"

    @field_validator("amount")
    @classmethod
    def amount_must_be_positive(cls, v: int) -> int:
        if v <= 0:
            raise ValueError("amount must be greater than 0 paise")
        return v

    @field_validator("date")
    @classmethod
    def date_must_be_valid(cls, v: str) -> str:
        # Raises ValueError if the string is not a valid ISO date
        DateType.fromisoformat(v)
        return v

    @field_validator("category", "description")
    @classmethod
    def must_not_be_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("field must not be empty")
        return v


# ---------------------------------------------------------------------------
# Single expense returned by the API
# ---------------------------------------------------------------------------
class ExpenseOut(BaseModel):
    id: str
    amount: int              # PAISE
    category: str
    description: str
    date: str
    created_at: str


# ---------------------------------------------------------------------------
# Response envelope for GET /expenses
# ---------------------------------------------------------------------------
class ExpenseListResponse(BaseModel):
    expenses: List[ExpenseOut]
    total: int               # sum of amount (PAISE) for the filtered result set
                             # computed server-side per constraint #7
